"""added description & genre_id columns

Revision ID: 6bb6473622db
Revises: 1dabb1f8788d
Create Date: 2025-12-02 09:38:21.753001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb6473622db'
down_revision: Union[str, None] = '1dabb1f8788d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogues', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('catalogues', sa.Column('genre_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'catalogues', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalogues', type_='foreignkey')
    op.drop_column('catalogues', 'genre_id')
    op.drop_column('catalogues', 'description')
    # ### end Alembic commands ###
